(cl:in-package car_interfaces-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPS_TIME-VAL
          GPS_TIME
          ANGRATERAWX-VAL
          ANGRATERAWX
          ANGRATERAWY-VAL
          ANGRATERAWY
          ANGRATERAWZ-VAL
          ANGRATERAWZ
          ACCELRAWX-VAL
          ACCELRAWX
          ACCELRAWY-VAL
          ACCELRAWY
          ACCELRAWZ-VAL
          ACCELRAWZ
          POSESIGMA-VAL
          POSESIGMA
          POSNSIGMA-VAL
          POSNSIGMA
          POSUSIGMA-VAL
          POSUSIGMA
          VELESIGMA-VAL
          VELESIGMA
          VELNSIGMA-VAL
          VELNSIGMA
          VELUSIGMA-VAL
          VELUSIGMA
          VELSIGMA-VAL
          VELSIGMA
          ACCELX-VAL
          ACCELX
          ACCELY-VAL
          ACCELY
          ACCELZ-VAL
          ACCELZ
          ANGLEHEADINGSIGMA-VAL
          ANGLEHEADINGSIGMA
          ANGLEPITCHSIGMA-VAL
          ANGLEPITCHSIGMA
          ANGLEROLLSIGMA-VAL
          ANGLEROLLSIGMA
          ANGRATEX-VAL
          ANGRATEX
          ANGRATEY-VAL
          ANGRATEY
          ANGRATEZ-VAL
          ANGRATEZ
          GPSNUMSATS2USED-VAL
          GPSNUMSATS2USED
          GPSNUMSATS-VAL
          GPSNUMSATS
          GPSNUMSATS2-VAL
          GPSNUMSATS2
          REAR_POSX-VAL
          REAR_POSX
          REAR_POSY-VAL
          REAR_POSY
          REAR_POSZ-VAL
          REAR_POSZ
          PROCESS_TIME-VAL
          PROCESS_TIME
))