(cl:in-package car_interfaces-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ID-VAL
          ID
          CARLENGTH-VAL
          CARLENGTH
          CARWIDTH-VAL
          CARWIDTH
          CARHEIGHT-VAL
          CARHEIGHT
          CENTEROFFSET-VAL
          CENTEROFFSET
          SIGNNUMBER-VAL
          SIGNNUMBER
          SIGNDATA-VAL
          SIGNDATA
          LIGHTDATA-VAL
          LIGHTDATA
          OBSTACLEDATA-VAL
          OBSTACLEDATA
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          WX-VAL
          WX
          WY-VAL
          WY
          WZ-VAL
          WZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          EASTVELOCITY-VAL
          EASTVELOCITY
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          SKYVELOCITY-VAL
          SKYVELOCITY
          CARSPEED-VAL
          CARSPEED
          STEERANGLE-VAL
          STEERANGLE
          GEARPOS-VAL
          GEARPOS
          BRAKETQ-VAL
          BRAKETQ
          PARKINGSTATE-VAL
          PARKINGSTATE
          SOC-VAL
          SOC
          BATTERYVOL-VAL
          BATTERYVOL
          BATTERYDISCHARGECUR-VAL
          BATTERYDISCHARGECUR
          CAR_RUN_MODE-VAL
          CAR_RUN_MODE
          THROTTLE_PERCENTAGE-VAL
          THROTTLE_PERCENTAGE
          BRAKING_PERCENTAGE-VAL
          BRAKING_PERCENTAGE
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          REVERSING_LIGHT-VAL
          REVERSING_LIGHT
          SPEAKER-VAL
          SPEAKER
          START_BUTTON-VAL
          START_BUTTON
          STOP_BUTTON-VAL
          STOP_BUTTON
          STATE-VAL
          STATE
          ERROR-VAL
          ERROR
          COTTON_PICKER_FAN_ENABLER_ACT-VAL
          COTTON_PICKER_FAN_ENABLER_ACT
          COTTON_BIN_UPPER_ACT-VAL
          COTTON_BIN_UPPER_ACT
          COTTON_BIN_LOWER_ACT-VAL
          COTTON_BIN_LOWER_ACT
          COTTON_BIN_TILTING_ACT-VAL
          COTTON_BIN_TILTING_ACT
          COTTON_BIN_RESTORE_ACT-VAL
          COTTON_BIN_RESTORE_ACT
          COTTON_UNLOAD_ACT-VAL
          COTTON_UNLOAD_ACT
          COTTON_PICKER_HEAD_HEIGHT-VAL
          COTTON_PICKER_HEAD_HEIGHT
          TARGET_PRIMARY_GEAR_ACT-VAL
          TARGET_PRIMARY_GEAR_ACT
          TARGET_ENGINESPEEDLEVEL_ACT-VAL
          TARGET_ENGINESPEEDLEVEL_ACT
          TARGET_SPEEDLEVER_PERCENTAGE_ACT-VAL
          TARGET_SPEEDLEVER_PERCENTAGE_ACT
          PROCESS_TIME-VAL
          PROCESS_TIME
))