(cl:in-package car_interfaces-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPS_TIME-VAL
          GPS_TIME
          POSLON-VAL
          POSLON
          POSLAT-VAL
          POSLAT
          POSALT-VAL
          POSALT
          VELE-VAL
          VELE
          VELN-VAL
          VELN
          VELU-VAL
          VELU
          VEL-VAL
          VEL
          ANGLEHEADING-VAL
          ANGLEHEADING
          ANGLEPITCH-VAL
          ANGLEPITCH
          ANGLEROLL-VAL
          ANGLEROLL
          SYSTEM_STATE-VAL
          SYSTEM_STATE
          GPSNUMSATSUSED-VAL
          GPSNUMSATSUSED
          SATELLITE_STATUS-VAL
          SATELLITE_STATUS
          GPSAGE-VAL
          GPSAGE
          STATE-VAL
          STATE
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          POSZ-VAL
          POSZ
          PROCESS_TIME-VAL
          PROCESS_TIME
))