(cl:in-package car_interfaces-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ID-VAL
          ID
          CENTEROFFSET-VAL
          CENTEROFFSET
          SIGNNUMBER-VAL
          SIGNNUMBER
          SIGNDATA-VAL
          SIGNDATA
          LIGHTDATA-VAL
          LIGHTDATA
          OBSTACLEDATA-VAL
          OBSTACLEDATA
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          POSZ-VAL
          POSZ
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          EASTVELOCITY-VAL
          EASTVELOCITY
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          SKYVELOCITY-VAL
          SKYVELOCITY
          CARSPEED-VAL
          CARSPEED
))