(cl:in-package lidar-msg)
(cl:export '(ID-VAL
          ID
          TYPE-VAL
          TYPE
          EXIST_CON-VAL
          EXIST_CON
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          DIS_X-VAL
          DIS_X
          DIS_Y-VAL
          DIS_Y
          DIS_Z-VAL
          DIS_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          OBJECT_X-VAL
          OBJECT_X
          OBJECT_Y-VAL
          OBJECT_Y
          OBJECT_Z-VAL
          OBJECT_Z
          CORE_X-VAL
          CORE_X
          CORE_Y-VAL
          CORE_Y
          CORE_Z-VAL
          CORE_Z
          ATTENTION_TYPE-VAL
          ATTENTION_TYPE
          MOTION_STATE-VAL
          MOTION_STATE
          AGE-VAL
          AGE
          TRA_ID-VAL
          TRA_ID
))