// Generated by gencpp from file car_interfaces/CameraObstacleInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_CAMERAOBSTACLEINTERFACE_H
#define CAR_INTERFACES_MESSAGE_CAMERAOBSTACLEINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace car_interfaces
{
template <class ContainerAllocator>
struct CameraObstacleInterface_
{
  typedef CameraObstacleInterface_<ContainerAllocator> Type;

  CameraObstacleInterface_()
    : timestamp(0.0)
    , id(0)
    , number(0)
    , obstacledata()
    , resultimage()
    , process_time(0.0)  {
    }
  CameraObstacleInterface_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , id(0)
    , number(0)
    , obstacledata(_alloc)
    , resultimage(_alloc)
    , process_time(0.0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint16_t _number_type;
  _number_type number;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _obstacledata_type;
  _obstacledata_type obstacledata;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _resultimage_type;
  _resultimage_type resultimage;

   typedef float _process_time_type;
  _process_time_type process_time;





  typedef boost::shared_ptr< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> const> ConstPtr;

}; // struct CameraObstacleInterface_

typedef ::car_interfaces::CameraObstacleInterface_<std::allocator<void> > CameraObstacleInterface;

typedef boost::shared_ptr< ::car_interfaces::CameraObstacleInterface > CameraObstacleInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::CameraObstacleInterface const> CameraObstacleInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.id == rhs.id &&
    lhs.number == rhs.number &&
    lhs.obstacledata == rhs.obstacledata &&
    lhs.resultimage == rhs.resultimage &&
    lhs.process_time == rhs.process_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "454b71629ff68db2d3a44afe4cb25c2a";
  }

  static const char* value(const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x454b71629ff68db2ULL;
  static const uint64_t static_value2 = 0xd3a44afe4cb25c2aULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/CameraObstacleInterface";
  }

  static const char* value(const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  timestamp  #时间戳\n"
"uint8  id  # 摄像机ID\n"
"uint16  number  # 障碍物数量\n"
"float32[]  obstacledata  #障碍物数据\n"
"sensor_msgs/Image  resultimage     # 障碍物检测结果图像\n"
"float32  process_time    # 进程处理时间\n"
"\n"
"\n"
"# 其中obstacledata格式float32[]为一维数组，储存按照[category ,length ,width ,height , x  ,y  ,z  ,v  ,latv ,category  ,length ,width ,height , x ,y ,z ,v ,latv ,……]存储，9个长度数据为一组\n"
"# int  category     # 障碍物类别， 0点目标；1小汽车；2卡车/客车；3行人；4摩托车/电动车；5自行车；6宽大目标（如墙面）；7reserved保留； 8traffic light； 9stop sign\n"
"# float  length       # 障碍物长度m，精度为0.01\n"
"# float  width       # 障碍物宽度m，精度为0.01\n"
"# float  height       # 障碍物高度m，精度为0.01\n"
"# float  x     # 障碍物的x坐标[米]，精度为0.01\n"
"# float  y   # 障碍物的y坐标[米]，精度为0.01\n"
"# float  z    # 障碍物的z坐标[米]，精度为0.01\n"
"# float  v=0    # 障碍物径向速度m/s，精度为0.01\n"
"# float  latv=0  # 障碍物的横向速度m/s，精度为0.01\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.id);
      stream.next(m.number);
      stream.next(m.obstacledata);
      stream.next(m.resultimage);
      stream.next(m.process_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraObstacleInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::CameraObstacleInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::CameraObstacleInterface_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "number: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.number);
    s << indent << "obstacledata[]" << std::endl;
    for (size_t i = 0; i < v.obstacledata.size(); ++i)
    {
      s << indent << "  obstacledata[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.obstacledata[i]);
    }
    s << indent << "resultimage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.resultimage);
    s << indent << "process_time: ";
    Printer<float>::stream(s, indent + "  ", v.process_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_CAMERAOBSTACLEINTERFACE_H
