// Generated by gencpp from file car_interfaces/LidarOriInterface.msg
// DO NOT EDIT!


#ifndef CAR_INTERFACES_MESSAGE_LIDARORIINTERFACE_H
#define CAR_INTERFACES_MESSAGE_LIDARORIINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_interfaces
{
template <class ContainerAllocator>
struct LidarOriInterface_
{
  typedef LidarOriInterface_<ContainerAllocator> Type;

  LidarOriInterface_()
    : state(false)  {
    }
  LidarOriInterface_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::car_interfaces::LidarOriInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_interfaces::LidarOriInterface_<ContainerAllocator> const> ConstPtr;

}; // struct LidarOriInterface_

typedef ::car_interfaces::LidarOriInterface_<std::allocator<void> > LidarOriInterface;

typedef boost::shared_ptr< ::car_interfaces::LidarOriInterface > LidarOriInterfacePtr;
typedef boost::shared_ptr< ::car_interfaces::LidarOriInterface const> LidarOriInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_interfaces::LidarOriInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_interfaces::LidarOriInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::LidarOriInterface_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_interfaces::LidarOriInterface_<ContainerAllocator1> & lhs, const ::car_interfaces::LidarOriInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_interfaces::LidarOriInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_interfaces::LidarOriInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_interfaces::LidarOriInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::car_interfaces::LidarOriInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_interfaces/LidarOriInterface";
  }

  static const char* value(const ::car_interfaces::LidarOriInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
;
  }

  static const char* value(const ::car_interfaces::LidarOriInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarOriInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_interfaces::LidarOriInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_interfaces::LidarOriInterface_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_INTERFACES_MESSAGE_LIDARORIINTERFACE_H
