// Generated by gencpp from file hmi/GlobalPathPlanningInterface.msg
// DO NOT EDIT!


#ifndef HMI_MESSAGE_GLOBALPATHPLANNINGINTERFACE_H
#define HMI_MESSAGE_GLOBALPATHPLANNINGINTERFACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hmi
{
template <class ContainerAllocator>
struct GlobalPathPlanningInterface_
{
  typedef GlobalPathPlanningInterface_<ContainerAllocator> Type;

  GlobalPathPlanningInterface_()
    : timestamp(0.0)
    , startpoint()
    , endpoint()
    , routedata()
    , process_time(0.0)
    , Global_Path_Segment_Index(0)
    , len_path(0)
    , last_point()
    , plan_over(0)
    , x_list()
    , y_list()  {
    }
  GlobalPathPlanningInterface_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , startpoint(_alloc)
    , endpoint(_alloc)
    , routedata(_alloc)
    , process_time(0.0)
    , Global_Path_Segment_Index(0)
    , len_path(0)
    , last_point(_alloc)
    , plan_over(0)
    , x_list(_alloc)
    , y_list(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _startpoint_type;
  _startpoint_type startpoint;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _endpoint_type;
  _endpoint_type endpoint;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _routedata_type;
  _routedata_type routedata;

   typedef float _process_time_type;
  _process_time_type process_time;

   typedef int32_t _Global_Path_Segment_Index_type;
  _Global_Path_Segment_Index_type Global_Path_Segment_Index;

   typedef int32_t _len_path_type;
  _len_path_type len_path;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _last_point_type;
  _last_point_type last_point;

   typedef int8_t _plan_over_type;
  _plan_over_type plan_over;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_list_type;
  _x_list_type x_list;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_list_type;
  _y_list_type y_list;





  typedef boost::shared_ptr< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalPathPlanningInterface_

typedef ::hmi::GlobalPathPlanningInterface_<std::allocator<void> > GlobalPathPlanningInterface;

typedef boost::shared_ptr< ::hmi::GlobalPathPlanningInterface > GlobalPathPlanningInterfacePtr;
typedef boost::shared_ptr< ::hmi::GlobalPathPlanningInterface const> GlobalPathPlanningInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator1> & lhs, const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.startpoint == rhs.startpoint &&
    lhs.endpoint == rhs.endpoint &&
    lhs.routedata == rhs.routedata &&
    lhs.process_time == rhs.process_time &&
    lhs.Global_Path_Segment_Index == rhs.Global_Path_Segment_Index &&
    lhs.len_path == rhs.len_path &&
    lhs.last_point == rhs.last_point &&
    lhs.plan_over == rhs.plan_over &&
    lhs.x_list == rhs.x_list &&
    lhs.y_list == rhs.y_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator1> & lhs, const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hmi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec3972cc1c6335e1c2839cc4a004782b";
  }

  static const char* value(const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec3972cc1c6335e1ULL;
  static const uint64_t static_value2 = 0xc2839cc4a004782bULL;
};

template<class ContainerAllocator>
struct DataType< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hmi/GlobalPathPlanningInterface";
  }

  static const char* value(const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  timestamp  #时间戳\n"
"float64[]  startpoint   #起点位置\n"
"float64[]   endpoint    #终点位置\n"
"string[]   routedata   #路径集合（所有途径点的集合）\n"
"float32  process_time    # 进程处理时间\n"
"int32 Global_Path_Segment_Index # 从1开始累加\n"
"\n"
"int32 len_path # 全局路径的长度\n"
"\n"
"#int8 Global_Path_End_Flag #终点置1，其他0\n"
"float32[]   last_point\n"
"\n"
"int8 plan_over #0-等待规划完成 1-本次规划结束\n"
"\n"
"float64[] x_list\n"
"float64[] y_list\n"
;
  }

  static const char* value(const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.startpoint);
      stream.next(m.endpoint);
      stream.next(m.routedata);
      stream.next(m.process_time);
      stream.next(m.Global_Path_Segment_Index);
      stream.next(m.len_path);
      stream.next(m.last_point);
      stream.next(m.plan_over);
      stream.next(m.x_list);
      stream.next(m.y_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalPathPlanningInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hmi::GlobalPathPlanningInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hmi::GlobalPathPlanningInterface_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "startpoint[]" << std::endl;
    for (size_t i = 0; i < v.startpoint.size(); ++i)
    {
      s << indent << "  startpoint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.startpoint[i]);
    }
    s << indent << "endpoint[]" << std::endl;
    for (size_t i = 0; i < v.endpoint.size(); ++i)
    {
      s << indent << "  endpoint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.endpoint[i]);
    }
    s << indent << "routedata[]" << std::endl;
    for (size_t i = 0; i < v.routedata.size(); ++i)
    {
      s << indent << "  routedata[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.routedata[i]);
    }
    s << indent << "process_time: ";
    Printer<float>::stream(s, indent + "  ", v.process_time);
    s << indent << "Global_Path_Segment_Index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Global_Path_Segment_Index);
    s << indent << "len_path: ";
    Printer<int32_t>::stream(s, indent + "  ", v.len_path);
    s << indent << "last_point[]" << std::endl;
    for (size_t i = 0; i < v.last_point.size(); ++i)
    {
      s << indent << "  last_point[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.last_point[i]);
    }
    s << indent << "plan_over: ";
    Printer<int8_t>::stream(s, indent + "  ", v.plan_over);
    s << indent << "x_list[]" << std::endl;
    for (size_t i = 0; i < v.x_list.size(); ++i)
    {
      s << indent << "  x_list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x_list[i]);
    }
    s << indent << "y_list[]" << std::endl;
    for (size_t i = 0; i < v.y_list.size(); ++i)
    {
      s << indent << "  y_list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HMI_MESSAGE_GLOBALPATHPLANNINGINTERFACE_H
