# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/FaultDiagnosisInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FaultDiagnosisInterface(genpy.Message):
  _md5sum = "ecaf07b9d1233a61400449644874e137"
  _type = "car_interfaces/FaultDiagnosisInterface"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 lidar_start        #0-未启动 1-启动
bool Gps_state_fault    #惯导通讯故障 False：异常；True：正常
bool can_state          #can通信故障False：异常；True：正常

"""
  __slots__ = ['lidar_start','Gps_state_fault','can_state']
  _slot_types = ['int8','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lidar_start,Gps_state_fault,can_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultDiagnosisInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.lidar_start is None:
        self.lidar_start = 0
      if self.Gps_state_fault is None:
        self.Gps_state_fault = False
      if self.can_state is None:
        self.can_state = False
    else:
      self.lidar_start = 0
      self.Gps_state_fault = False
      self.can_state = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.lidar_start, _x.Gps_state_fault, _x.can_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.lidar_start, _x.Gps_state_fault, _x.can_state,) = _get_struct_b2B().unpack(str[start:end])
      self.Gps_state_fault = bool(self.Gps_state_fault)
      self.can_state = bool(self.can_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.lidar_start, _x.Gps_state_fault, _x.can_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.lidar_start, _x.Gps_state_fault, _x.can_state,) = _get_struct_b2B().unpack(str[start:end])
      self.Gps_state_fault = bool(self.Gps_state_fault)
      self.can_state = bool(self.can_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2B = None
def _get_struct_b2B():
    global _struct_b2B
    if _struct_b2B is None:
        _struct_b2B = struct.Struct("<b2B")
    return _struct_b2B
