# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/LaneRecognitionInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LaneRecognitionInterface(genpy.Message):
  _md5sum = "591a0ed90f206f06a64e5af5b01b3f9e"
  _type = "car_interfaces/LaneRecognitionInterface"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64  timestamp  #时间戳
uint8  id  # 摄像头ID
float32  centeroffset     # 车辆相对于车道中心线偏移的距离，默认0
float32  a0     # 左侧车道中心线的表达式：y = a0+a1*x+ a2*x^2+a3*x^3；
float32  a1     # 左侧车道中心线的表达式：y = a0+a1*x+ a2*x^2+a3*x^3；
float32  a2     # 左侧车道中心线的表达式：y = a0+a1*x+ a2*x^2+a3*x^3；
float32  a3     # 左侧车道中心线的表达式：y = a0+a1*x+ a2*x^2+a3*x^3；sensor_msgs/Image  resultimage     # 融合后的车道线识别图像
float32  process_time    # 进程处理时间


"""
  __slots__ = ['timestamp','id','centeroffset','a0','a1','a2','a3','process_time']
  _slot_types = ['float64','uint8','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,id,centeroffset,a0,a1,a2,a3,process_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaneRecognitionInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.id is None:
        self.id = 0
      if self.centeroffset is None:
        self.centeroffset = 0.
      if self.a0 is None:
        self.a0 = 0.
      if self.a1 is None:
        self.a1 = 0.
      if self.a2 is None:
        self.a2 = 0.
      if self.a3 is None:
        self.a3 = 0.
      if self.process_time is None:
        self.process_time = 0.
    else:
      self.timestamp = 0.
      self.id = 0
      self.centeroffset = 0.
      self.a0 = 0.
      self.a1 = 0.
      self.a2 = 0.
      self.a3 = 0.
      self.process_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dB6f().pack(_x.timestamp, _x.id, _x.centeroffset, _x.a0, _x.a1, _x.a2, _x.a3, _x.process_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp, _x.id, _x.centeroffset, _x.a0, _x.a1, _x.a2, _x.a3, _x.process_time,) = _get_struct_dB6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dB6f().pack(_x.timestamp, _x.id, _x.centeroffset, _x.a0, _x.a1, _x.a2, _x.a3, _x.process_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp, _x.id, _x.centeroffset, _x.a0, _x.a1, _x.a2, _x.a3, _x.process_time,) = _get_struct_dB6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dB6f = None
def _get_struct_dB6f():
    global _struct_dB6f
    if _struct_dB6f is None:
        _struct_dB6f = struct.Struct("<dB6f")
    return _struct_dB6f
