# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/RadarObstacleInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarObstacleInterface(genpy.Message):
  _md5sum = "d72c4e0d3fc62d79de85a43eb6d4cf59"
  _type = "car_interfaces/RadarObstacleInterface"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64  timestamp  #时间戳
uint8  id  # 毫米波雷达ID
uint16  number  #障碍物数量
float32[]  obstacledata  #障碍物数据
float32  process_time    # 进程处理时间
#其中obstacledata格式float32[]为一维数组，储存按照[x  ,y  ,z  ,v  , x ,y ,z ,v ,latv ,……]存储49个长度数据为一组
# float  length       # 障碍物长度m，精度为0.01
# float  width       # 障碍物宽度m，精度为0.01
# float  height       # 障碍物高度m，精度为0.01
# float  x     # 障碍物的x坐标[米]，精度为0.01
# float  y   # 障碍物的y坐标[米]，精度为0.01
# float  z    # 障碍物的z坐标[米]，精度为0.01
# float  v=0    # 障碍物径向速度m/s，精度为0.01
# float  latv=0  # 障碍物的横向速度m/s，精度为0.01"""
  __slots__ = ['timestamp','id','number','obstacledata','process_time']
  _slot_types = ['float64','uint8','uint16','float32[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,id,number,obstacledata,process_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarObstacleInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.id is None:
        self.id = 0
      if self.number is None:
        self.number = 0
      if self.obstacledata is None:
        self.obstacledata = []
      if self.process_time is None:
        self.process_time = 0.
    else:
      self.timestamp = 0.
      self.id = 0
      self.number = 0
      self.obstacledata = []
      self.process_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dBH().pack(_x.timestamp, _x.id, _x.number))
      length = len(self.obstacledata)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.obstacledata))
      _x = self.process_time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.timestamp, _x.id, _x.number,) = _get_struct_dBH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.obstacledata = s.unpack(str[start:end])
      start = end
      end += 4
      (self.process_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dBH().pack(_x.timestamp, _x.id, _x.number))
      length = len(self.obstacledata)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.obstacledata.tostring())
      _x = self.process_time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.timestamp, _x.id, _x.number,) = _get_struct_dBH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.obstacledata = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (self.process_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dBH = None
def _get_struct_dBH():
    global _struct_dBH
    if _struct_dBH is None:
        _struct_dBH = struct.Struct("<dBH")
    return _struct_dBH
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
