# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_interfaces/VehOperatingStateInterface.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehOperatingStateInterface(genpy.Message):
  _md5sum = "04f41a0b98d40a7eebbc487cf38ee657"
  _type = "car_interfaces/VehOperatingStateInterface"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64  timestamp  # 数据帧时间戳
int8 VehOperat_Status #  1 - 人工驾驶;2 - 上电自检; 3 - 车辆起步; 4 - 进入棉田; 5 - 开始采棉; 6-暂停工作; 7- 卸载棉花;8-完工收车
float32  process_time    # 进程处理时间"""
  __slots__ = ['timestamp','VehOperat_Status','process_time']
  _slot_types = ['float64','int8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,VehOperat_Status,process_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehOperatingStateInterface, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.VehOperat_Status is None:
        self.VehOperat_Status = 0
      if self.process_time is None:
        self.process_time = 0.
    else:
      self.timestamp = 0.
      self.VehOperat_Status = 0
      self.process_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dbf().pack(_x.timestamp, _x.VehOperat_Status, _x.process_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp, _x.VehOperat_Status, _x.process_time,) = _get_struct_dbf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dbf().pack(_x.timestamp, _x.VehOperat_Status, _x.process_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp, _x.VehOperat_Status, _x.process_time,) = _get_struct_dbf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dbf = None
def _get_struct_dbf():
    global _struct_dbf
    if _struct_dbf is None:
        _struct_dbf = struct.Struct("<dbf")
    return _struct_dbf
