(cl:defpackage hmi-msg
  (:use )
  (:export
   "<CARACTIONINTERFACE>"
   "CARACTIONINTERFACE"
   "<CARORIINTERFACE>"
   "CARORIINTERFACE"
   "<FAULTDIAGNOSISINTERFACE>"
   "FAULTDIAGNOSISINTERFACE"
   "<GLOBALPATHPLANNINGINTERFACE>"
   "GLOBALPATHPLANNINGINTERFACE"
   "<GPSIMUINTERFACE>"
   "GPSIMUINTERFACE"
   "<HMISTARTENDPOINTINTERFACE>"
   "HMISTARTENDPOINTINTERFACE"
   "<NODEPOINTSINTERFACE>"
   "NODEPOINTSINTERFACE"
   "<PARAMOPTIMIZEINTERFACE>"
   "PARAMOPTIMIZEINTERFACE"
   "<PATHSPEEDCTRLINTERFACE>"
   "PATHSPEEDCTRLINTERFACE"
   "<VEHOPERATINGDATA>"
   "VEHOPERATINGDATA"
  ))

